// *** Your name: Auraud Zarafshar
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.*;

public class CirclePainterWindow extends JFrame implements ActionListener {

	private CirclePanel circlePanel;
	private CirclePanelListener circlePanelListener;
	private JTextField radiusTextField;

	public CirclePainterWindow() {
		circlePanel = new CirclePanel();
		circlePanelListener = new CirclePanelListener(circlePanel);
		JPanel mainPanel = new JPanel();
		JPanel settingsPanel = new JPanel();
		radiusTextField = new JTextField(5);
		settingsPanel.add(radiusTextField);
		mainPanel.setLayout(new BorderLayout());
		mainPanel.add(circlePanel, BorderLayout.CENTER);
		mainPanel.add(settingsPanel, BorderLayout.SOUTH);
		// Create a panel for the buttons, label, and text field
		// and then add it in the south position.
		// Remember to add this as an ActionListener for the
		// buttons and text field.

		// The line "radiusTextField.selectAll();" will be helpful for completing your requirements.
		// You can look up what it does.
		// As for where it goes, think about which section of your code it would be most helpful in.

		JMenuBar menuBar = new JMenuBar();

		// Create a Color menu for the menu bar with Red, Blue, and Green menu items.
		// Remember to add this as an ActionListener for the menu items.
		JMenu colorMenu = new JMenu("Color");

		menuBar.add(colorMenu);
		JMenuItem redItem = new JMenuItem("Red");
		JMenuItem blueItem = new JMenuItem("Blue");
		JMenuItem greenItem = new JMenuItem("Green");
		colorMenu.add(redItem);
		colorMenu.add(blueItem);
		colorMenu.add(greenItem);
		redItem.addActionListener(this);
		blueItem.addActionListener(this);
		greenItem.addActionListener(this);
		this.setContentPane(mainPanel);
		this.setJMenuBar(menuBar);

	}


	@Override
	public void actionPerformed(ActionEvent ev) {
		// write code to respond appropriately to all of the possible
		// ActionEvents generated by the menu items, buttons, and text field
		String s = ev.getActionCommand();

		if (s == null) {
			return;
		} else if (s.equals("Red")) {
			circlePanelListener.setColorOfNewlyCreatedCircles(Color.RED);
		} else if (s.equals("Blue")) {
			circlePanelListener.setColorOfNewlyCreatedCircles(Color.BLUE);
		} else if (s.equals("Green")) {
			circlePanelListener.setColorOfNewlyCreatedCircles(Color.GREEN);
		}


	}


}
